FROM golang:1.15-alpine as compile
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates
WORKDIR /app
COPY . /app
ENV GO111MODULE=on
RUN go get -t -v ./...
ENV GOOS=linux
ENV GOARCH=amd64
ENTRYPOINT go build -ldflags="-w -s" -o /go/bin/ts2-server

FROM golang:1.15 as testcoverage
WORKDIR /app
COPY . /app
ENTRYPOINT go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
